config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :locations, only: %i[index show] do
    get :export
  end

  root to: 'locations#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# * Base record for the application
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/open_weather/forecast.rb
# frozen_string_literal: true

module OpenWeather
  class Forecast
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :date_time
    attribute :temp
    attribute :feels_like
    attribute :weather
    attribute :humidity
    attribute :wind_speed

    def weather_text
      weather_array? ? weather.join(', ') : weather
    end

    private

    def weather_array?
      weather.present? && weather.is_a?(Array)
    end
  end
end

app/models/open_weather/forecast_day.rb
# frozen_string_literal: true

module OpenWeather
  class ForecastDay
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :date
    attribute :key
    attribute :forecasts

    %w[temp feels_like humidity wind_speed].each do |field|
      define_method "average_#{field}".to_sym do
        values = forecasts.map { |forecast| forecast.send(field.to_sym).to_f }
        values.sum / values.size
      end
    end

    def date_text
      date.strftime('%d/%m/%Y')
    end
  end
end

app/models/open_weather/location.rb
# frozen_string_literal: true

module OpenWeather
  class Location
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :lat
    attribute :lng
    attribute :name
    attribute :country
  end
end

app/models/open_weather/location_search.rb
# frozen_string_literal: true

module OpenWeather
  class LocationSearch
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :term
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  before_action :set_location_search, only: :index
  before_action :set_location, only: %i[show export]
  before_action :capture_forecast, only: %i[show export]

  def index
    @locations = searching? ? search_data : []
  end

  def show
    @current_weather = Weather::Client::CurrentService.find(@location.lat, @location.lng)
  end

  def export
    @export = WeatherExportService.new(params[:name], @forecasts)

    send_data @export.export, filename: @export.filename
  end

  private

  def set_location_search
    @search = OpenWeather::LocationSearch.new(search_params)
  end

  def set_location
    @location = OpenWeather::Location.new(
      name: params[:name],
      lat: params[:lat],
      lng: params[:lng],
      country: params[:location_id].presence || params[:id]
    )
  end

  def capture_forecast
    @forecasts = Weather::Client::ForecastService.find(@location.lat, @location.lng)
  end

  def searching?
    @search.term.present?
  end

  def search_data
    @search_data ||= Weather::Client::GeoLocationService.search(@search.term)
  end

  def search_params
    params.require(:search)&.permit(:term) if params[:search].present?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# * Base Helper for the application
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuiceTechTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <nav class="nav">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Location Search", locations_path %></li>
        </ul>
      </nav>
    </header>
    
    <main>
      <%= yield %>
    </main>
    <footer>
      <span>&copy; 2023</span>
    </footer>
  </body>
</html>

app/views/locations/index.html.erb
<article>
  <div class="box box--small">
    <h1>Location Search</h1>

    <%= form_with(model: @search, scope: 'search', local: false, url: locations_path, method: :get) do |f| %>
      <div class="field">
        <%= f.label :term %>
        <%= f.text_field :term %>
      </div>

      <%= f.submit :search, class: 'button' %>
    <% end %>
  </div>

  <% if @locations.any? %>
    <div data-target="location_results">
      <% @locations.each do |location| %>
        <div class="box box--small result-box">
          <%= content_tag(:div, location.name, class: 'result-box__name') %>
          <%= content_tag(:div, location.country, class: 'result-box__country') %>
          <div class="result-box__actions">
            <%= 
              link_to(
                'Show',
                location_path(
                  id: location.country,
                  name: location.name,
                  lat: location.lat,
                  lng: location.lng
                ),
                class: 'button' 
              ) %>
            </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="box box--small" data-target="message">
      <p>No locations found.</p>
    </div>
  <% end %>
</article>

app/views/locations/show.html.erb
<article>
  <div class="header--split">
    <%= link_to "<", locations_path, class: 'header--split__back' %>
    <%= content_tag(:h1, @location.name, class: 'header--split__title') %>
  </div>

  <div class="box box--small" data-target="current_weather">
    <h2>Current</h2>

    <p data-target="current_temp" class="highlight"><%= @current_weather.temp %>&deg;C</p>
    <p data-target="current_description" class="subheading"><%= @current_weather.weather_text %></p>

    <ul>
      <li><b>Feels Like:</b> <%= @current_weather.feels_like %>&deg;C</li>
      <li><b>Humidity:</b> <%= @current_weather.humidity %>%</li>
      <li><b>Wind Speed:</b> <%= @current_weather.wind_speed %> KPH</li>
    </ul>
  </div>

  <div data-target="forecast">
    <div class="header--action">
      <h2 class="header--action__title">Forecast</h2>
      <div class="header--action__buttons">
        <%=
          link_to(
              "Export (CSV)",
              location_export_path(
                location_id: params[:id],
                lat: params[:lat],
                lng: params[:lng],
                name: params[:name]
              ),
              download: true,
              class: 'button'
          ) 
        %>
      </div>
    </div>

    <% if @forecasts.any? %>
      <% @forecasts.each do |day| %>
        <div class="box" data-target="forecast_<%= day.key %>">
          <h3><%= day.date_text %></h3>
          <div class="key-details">
            <div>
              <p class="highlight highlight--small"><%= day.average_temp.round(2) %>&deg;C</p>
              <p>Average Temp</p>
            </div>

            <div>
              <p class="highlight highlight--small"><%= day.average_feels_like.round(2) %>&deg;C</p>
              <p>Average Feels Like</p>
            </div>

            <div>
              <p class="highlight highlight--small"><%= day.average_humidity.round(2) %>%</p>
              <p>Average Humidity</p>
            </div>

            <div>
              <p class="highlight highlight--small"><%= day.average_wind_speed.round(2) %> KPH</p>
              <p>Average Wind Speed</p>
            </div>
          </div>

          <div class="forecast_breakdown">
            <% day.forecasts.each do |forecast|%>
              <div data-target="forecast_hour_<%= forecast.date_time.to_i %>">
                <h4><%= forecast.date_time.strftime("%H:%M") %></h4>
                <ul>
                  <li><b>Temp:</b> <%= forecast.temp %>&deg;C</li>
                  <li><b>Weather:</b> <%= forecast.weather_text %></li>
                  <li><b>Feels Like:</b> <%= forecast.feels_like %>&deg;C</li>
                  <li><b>Humidity:</b> <%= forecast.humidity %>%</li>
                  <li><b>Wind Speed:</b> <%= forecast.wind_speed %>KPH</li>
                </ul>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>

    <% end %>
  </div>
</article>